// <auto-generated />
using System;
using Entity_Musteri_Siparis_Project;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Musteri_Siparis_Project.Migrations
{
    [DbContext(typeof(MusteriSiparisDbContext))]
    [Migration("20230827185104_AdminPasswordVariableString")]
    partial class AdminPasswordVariableString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Musteri_Siparis_Project.Admin", b =>
                {
                    b.Property<int>("AdminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminID"));

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminID");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Entity_Musteri_Siparis_Project.Musteri", b =>
                {
                    b.Property<int>("MusteriID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriID"));

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("MusteriTel")
                        .HasColumnType("bigint");

                    b.Property<int?>("SiparisID")
                        .HasColumnType("int");

                    b.HasKey("MusteriID");

                    b.HasIndex("SiparisID");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Entity_Musteri_Siparis_Project.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiparisID"));

                    b.Property<int>("MusteriID")
                        .HasColumnType("int");

                    b.Property<string>("SiparisDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiparisTarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UrunID")
                        .HasColumnType("int");

                    b.HasKey("SiparisID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("Entity_Musteri_Siparis_Project.Musteri", b =>
                {
                    b.HasOne("Entity_Musteri_Siparis_Project.Siparis", "Siparis")
                        .WithMany("Musteri")
                        .HasForeignKey("SiparisID");

                    b.Navigation("Siparis");
                });

            modelBuilder.Entity("Entity_Musteri_Siparis_Project.Siparis", b =>
                {
                    b.Navigation("Musteri");
                });
#pragma warning restore 612, 618
        }
    }
}
